name: Test CI
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Test action
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Action
        id: action_run
        uses: ./
        with:
          file_path: .ci-helpers/file-status.yaml
      - name: Get the status
        run: echo "Status in file is ${{ steps.action_run.outputs.status }}"